/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gtdev_webapps_deschat_controllers_DESController */

#ifndef _Included_org_gtdev_webapps_deschat_controllers_DESController
#define _Included_org_gtdev_webapps_deschat_controllers_DESController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gtdev_webapps_deschat_controllers_DESController
 * Method:    des_init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gtdev_webapps_deschat_controllers_DESController_des_1init
        (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_gtdev_webapps_deschat_controllers_DESController
 * Method:    des_get_inited
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_gtdev_webapps_deschat_controllers_DESController_des_1get_1inited
        (JNIEnv *, jobject);

/*
 * Class:     org_gtdev_webapps_deschat_controllers_DESController
 * Method:    des_enc
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gtdev_webapps_deschat_controllers_DESController_des_1enc
        (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_gtdev_webapps_deschat_controllers_DESController
 * Method:    des_deInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gtdev_webapps_deschat_controllers_DESController_des_1deInit
        (JNIEnv *, jobject);

/*
 * Class:     org_gtdev_webapps_deschat_controllers_DESController
 * Method:    des_fileEnc
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gtdev_webapps_deschat_controllers_DESController_des_1fileEnc
        (JNIEnv *, jobject, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif